sudo: required
dist: bionic
language: java
jdk:
  - oraclejdk11
python:
  - "3.6"
services: docker
before_install:
  - sudo apt-get update
  - echo "Estamos na pasta do docker"
  - mvn clean package
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest-with-spring-boot-udemy:latest edmarjunior17/rest-with-spring-boot-udemy:$TRAVIS_JOB_ID;
    docker push edmarjunior17/rest-with-spring-boot-udemy:$TRAVIS_JOB_ID;
  on:
    branch: master
after_success:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 - V
  - pip3 uninstall wheel
  - pip3 install wheel
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 802261757212.dkr.ecr.sa-east-1.amazonaws.com
  - docker tag rest-with-spring-boot-udemy:latest $IMAGE_REPO_URL:$TRAVIS_JOB_ID
  - docker push $IMAGE_REPO_URL:$TRAVIS_JOB_ID
  - add-apt-repository ppa:eugenesan/ppa
  - apt-get update
  - apt-get install jq -y
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo -a tee /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy
  - echo "AWS ECS-Deploy configurado!"
  - ecs-deploy -c $CLUSTER_NAME -n $SERVICE_NAME -i $IMAGE_REPO_URL:$TRAVIS_JOB_ID -r $AWS_DEFAULT_REGION -t 240
notifications:
  email: false