language: bash
services: docker
before_install:
  - echo "Estamos na pasta do docker"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push edmarjunior17/rest-with-spring-boot-udemy;
    docker push edmarjunior17/mysql-rest-with-spring-boot-udemy;
  on:
    branch: master
notifications:
  email: false